# Use the official Node.js image as our base
FROM node:20.15.1

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install app dependencies
RUN npm install nodemon -g 

# Copy the rest of our app's source code into the container
COPY . .

# Expose the port the app will run on
EXPOSE 5503

# The command to run our app
CMD ["npm", "run", "dev"]
